/********************************************************************
* dicts/LinuxRHFC8/TPart_idDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/LinuxRHFC8/TPart_idDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTPart_idDict();
extern void G__cpp_setup_inheritanceTPart_idDict();
extern void G__cpp_setup_typetableTPart_idDict();
extern void G__cpp_setup_memvarTPart_idDict();
extern void G__cpp_setup_globalTPart_idDict();
extern void G__cpp_setup_memfuncTPart_idDict();
extern void G__cpp_setup_funcTPart_idDict();
extern void G__set_cpp_environmentTPart_idDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TPart_id.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPart_idDictLN_TClass;
extern G__linked_taginfo G__TPart_idDictLN_TBuffer;
extern G__linked_taginfo G__TPart_idDictLN_TMemberInspector;
extern G__linked_taginfo G__TPart_idDictLN_TObject;
extern G__linked_taginfo G__TPart_idDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TPart_idDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TPart_idDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPart_idDictLN_TObjArray;
extern G__linked_taginfo G__TPart_idDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TPart_idDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPart_idDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TPart_idDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TPart_idDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPart_idDictLN_TTree;
extern G__linked_taginfo G__TPart_idDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TPart_idDictLN_TStopwatch;
extern G__linked_taginfo G__TPart_idDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TPart_idDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TPart_idDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TPart_idDictLN_TLorentzVector;
extern G__linked_taginfo G__TPart_idDictLN_TF1;
extern G__linked_taginfo G__TPart_idDictLN_TH1F;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TPart_idDictLN_TClasTool;
extern G__linked_taginfo G__TPart_idDictLN_TCounterCol;
extern G__linked_taginfo G__TPart_idDictLN_TInterrupt;
extern G__linked_taginfo G__TPart_idDictLN_TH2F;
extern G__linked_taginfo G__TPart_idDictLN_TH3D;
extern G__linked_taginfo G__TPart_idDictLN_TPart_ident_ct;
extern G__linked_taginfo G__TPart_idDictLN_TPart_id;

/* STUB derived class for protected member access */
