/********************************************************************
* dicts/Linux64RHEL5/cc_stuffDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL5/cc_stuffDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablecc_stuffDict();
extern void G__cpp_setup_inheritancecc_stuffDict();
extern void G__cpp_setup_typetablecc_stuffDict();
extern void G__cpp_setup_memvarcc_stuffDict();
extern void G__cpp_setup_globalcc_stuffDict();
extern void G__cpp_setup_memfunccc_stuffDict();
extern void G__cpp_setup_funccc_stuffDict();
extern void G__set_cpp_environmentcc_stuffDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "cc_stuff.h"

#ifndef G__MEMFUNCBODY
#endif


/* STUB derived class for protected member access */
