/********************************************************************
* dicts/Linux_Ubuntu12.04-x86_64-gcc4.6/fidc_cut_allDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux_Ubuntu12.04-x86_64-gcc4.6/fidc_cut_allDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablefidc_cut_allDict();
extern void G__cpp_setup_inheritancefidc_cut_allDict();
extern void G__cpp_setup_typetablefidc_cut_allDict();
extern void G__cpp_setup_memvarfidc_cut_allDict();
extern void G__cpp_setup_globalfidc_cut_allDict();
extern void G__cpp_setup_memfuncfidc_cut_allDict();
extern void G__cpp_setup_funcfidc_cut_allDict();
extern void G__set_cpp_environmentfidc_cut_allDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "fidc_cut_all.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fidc_cut_allDictLN_TString;
extern G__linked_taginfo G__fidc_cut_allDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TVector3;
extern G__linked_taginfo G__fidc_cut_allDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TF1;
extern G__linked_taginfo G__fidc_cut_allDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__fidc_cut_allDictLN_TFidCut;

/* STUB derived class for protected member access */
