/********************************************************************
* dicts/Linux64RHEL4/TPart_ident_ctDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL4/TPart_ident_ctDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTPart_ident_ctDict();
extern void G__cpp_setup_inheritanceTPart_ident_ctDict();
extern void G__cpp_setup_typetableTPart_ident_ctDict();
extern void G__cpp_setup_memvarTPart_ident_ctDict();
extern void G__cpp_setup_globalTPart_ident_ctDict();
extern void G__cpp_setup_memfuncTPart_ident_ctDict();
extern void G__cpp_setup_funcTPart_ident_ctDict();
extern void G__set_cpp_environmentTPart_ident_ctDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "TPart_ident_ct.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPart_ident_ctDictLN_TObject;
extern G__linked_taginfo G__TPart_ident_ctDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TEVNTClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TECPBClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TSCPBClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TDCPBClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TCCPBClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TGSIMClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMCHDClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TMCTKClass;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TClasTool;
extern G__linked_taginfo G__TPart_ident_ctDictLN_TPart_ident_ct;

/* STUB derived class for protected member access */
