/********************************************************************
* dicts/Linux64RHEL4/TArray_7Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL4/TArray_7Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTArray_7Dict();
extern void G__cpp_setup_inheritanceTArray_7Dict();
extern void G__cpp_setup_typetableTArray_7Dict();
extern void G__cpp_setup_memvarTArray_7Dict();
extern void G__cpp_setup_globalTArray_7Dict();
extern void G__cpp_setup_memfuncTArray_7Dict();
extern void G__cpp_setup_funcTArray_7Dict();
extern void G__set_cpp_environmentTArray_7Dict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "TArray_7.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TArray_7DictLN_TClass;
extern G__linked_taginfo G__TArray_7DictLN_TBuffer;
extern G__linked_taginfo G__TArray_7DictLN_TMemberInspector;
extern G__linked_taginfo G__TArray_7DictLN_TObject;
extern G__linked_taginfo G__TArray_7DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TArray_7DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TArray_7DictLN_TArray_7;

/* STUB derived class for protected member access */
