//
// File generated by /net/home/lzana/root/bin/rootcint at Mon Oct 29 22:54:10 2007

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TArray_7Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TArray_7_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TArray_7(void *p);
   static void deleteArray_TArray_7(void *p);
   static void destruct_TArray_7(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TArray_7*)
   {
      ::TArray_7 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TArray_7 >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TArray_7", ::TArray_7::Class_Version(), "./TArray_7.h", 7,
                  typeid(::TArray_7), DefineBehavior(ptr, ptr),
                  &::TArray_7::Dictionary, isa_proxy, 0,
                  sizeof(::TArray_7) );
      instance.SetDelete(&delete_TArray_7);
      instance.SetDeleteArray(&deleteArray_TArray_7);
      instance.SetDestructor(&destruct_TArray_7);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TArray_7*)
   {
      return GenerateInitInstanceLocal((::TArray_7*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TArray_7*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TArray_7::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TArray_7::Class_Name()
{
   return "TArray_7";
}

//______________________________________________________________________________
const char *TArray_7::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TArray_7*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TArray_7::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TArray_7*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TArray_7::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TArray_7*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TArray_7::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TArray_7*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TArray_7::Streamer(TBuffer &R__b)
{
   // Stream an object of class TArray_7.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> fn_bin_x;
      R__b >> fn_bin_y;
      R__b >> fn_bin_z;
      R__b >> fn_bin_t;
      R__b >> fn_bin_i;
      R__b >> fn_bin_j;
      R__b >> fn_bin_k;
      R__b >> fn_bin_total;
      //R__b.ReadArray(fArray);
      R__b.CheckByteCount(R__s, R__c, TArray_7::IsA());
   } else {
      R__c = R__b.WriteVersion(TArray_7::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << fn_bin_x;
      R__b << fn_bin_y;
      R__b << fn_bin_z;
      R__b << fn_bin_t;
      R__b << fn_bin_i;
      R__b << fn_bin_j;
      R__b << fn_bin_k;
      R__b << fn_bin_total;
      //R__b.WriteArray(fArray, __COUNTER__);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TArray_7::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TArray_7.
      TClass *R__cl = ::TArray_7::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fn_bin_x", &fn_bin_x);
      R__insp.Inspect(R__cl, R__parent, "fn_bin_y", &fn_bin_y);
      R__insp.Inspect(R__cl, R__parent, "fn_bin_z", &fn_bin_z);
      R__insp.Inspect(R__cl, R__parent, "fn_bin_t", &fn_bin_t);
      R__insp.Inspect(R__cl, R__parent, "fn_bin_i", &fn_bin_i);
      R__insp.Inspect(R__cl, R__parent, "fn_bin_j", &fn_bin_j);
      R__insp.Inspect(R__cl, R__parent, "fn_bin_k", &fn_bin_k);
      R__insp.Inspect(R__cl, R__parent, "fn_bin_total", &fn_bin_total);
      R__insp.Inspect(R__cl, R__parent, "*fArray", &fArray);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TArray_7(void *p) {
      delete ((::TArray_7*)p);
   }
   static void deleteArray_TArray_7(void *p) {
      delete [] ((::TArray_7*)p);
   }
   static void destruct_TArray_7(void *p) {
      typedef ::TArray_7 current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TArray_7

/********************************************************
* dicts/Linux64RHEL4/TArray_7Dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTArray_7Dict();

extern "C" void G__set_cpp_environmentTArray_7Dict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TArray_7.h");
  G__cpp_reset_tagtableTArray_7Dict();
}
#include <new>
extern "C" int G__cpp_dllrevTArray_7Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TArray_7 */
static int G__TArray_7Dict_183_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TArray_7* p = NULL;
   long gvp = G__getgvp();
   //m: 7
   if ((gvp == G__PVOID) || (gvp == 0)) {
     p = new TArray_7(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]));
   } else {
     p = new((void*) gvp) TArray_7(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TArray_7* p = NULL;
   long gvp = G__getgvp();
   //m: 1
   if ((gvp == G__PVOID) || (gvp == 0)) {
     p = new TArray_7(*(TArray_7*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) TArray_7(*(TArray_7*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArray_7*) G__getstructoffset())->operator=(*(TArray_7*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArray_7* pobj;
         TArray_7 xobj = ((TArray_7*) G__getstructoffset())->operator-();
         pobj = new TArray_7(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArray_7* pobj;
         TArray_7 xobj = ((TArray_7*) G__getstructoffset())->operator+(*(TArray_7*) libp->para[0].ref);
         pobj = new TArray_7(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArray_7* pobj;
         TArray_7 xobj = ((TArray_7*) G__getstructoffset())->operator-(*(TArray_7*) libp->para[0].ref);
         pobj = new TArray_7(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArray_7* pobj;
         TArray_7 xobj = ((TArray_7*) G__getstructoffset())->operator*(*(TArray_7*) libp->para[0].ref);
         pobj = new TArray_7(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArray_7* pobj;
         TArray_7 xobj = ((TArray_7*) G__getstructoffset())->operator/(*(TArray_7*) libp->para[0].ref);
         pobj = new TArray_7(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const float& obj = ((TArray_7*) G__getstructoffset())->Value(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]));
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TArray_7::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TArray_7::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TArray_7::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TArray_7::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TArray_7*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArray_7*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref, (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArray_7*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArray_7*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TArray_7::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TArray_7::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TArray_7::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TArray_7Dict_183_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TArray_7::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TArray_7 G__TTArray_7;
static int G__TArray_7Dict_183_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (TArray_7*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TArray_7*) (soff+(sizeof(TArray_7)*i)))->~G__TTArray_7();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (TArray_7*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((TArray_7*) (soff))->~G__TTArray_7();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TArray_7 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTArray_7Dict {
 public:
  G__Sizep2memfuncTArray_7Dict() {p=&G__Sizep2memfuncTArray_7Dict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTArray_7Dict::*p)();
};

size_t G__get_sizep2memfuncTArray_7Dict()
{
  G__Sizep2memfuncTArray_7Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTArray_7Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7))) {
     TArray_7 *G__Lderived;
     G__Lderived=(TArray_7*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7),G__get_linked_tagnum(&G__TArray_7DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTArray_7Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__TArray_7DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TArray_7DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TArray_7DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TArray_7DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TArray_7DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TArray_7 */
static void G__setup_memvarTArray_7(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7));
   { TArray_7 *p; p=(TArray_7*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_x=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_y=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_z=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_t=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_i=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_j=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_k=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,2,"fn_bin_total=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,70,0,0,-1,-1,-1,2,"fArray=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TArray_7DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTArray_7Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTArray_7(void) {
   /* TArray_7 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7));
   G__memfunc_setup("TArray_7",745,G__TArray_7Dict_183_0_1, 105, G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7), -1, 0, 7, 1, 1, 0, 
"i - - 0 - n_x i - - 0 - n_y "
"i - - 0 - n_z i - - 0 - n_t "
"i - - 0 - n_i i - - 0 - n_j "
"i - - 0 - n_k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TArray_7",745,G__TArray_7Dict_183_0_2, 105, G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7), -1, 0, 1, 1, 1, 0, "u 'TArray_7' - 11 - Array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__TArray_7Dict_183_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TArray_7' - 1 - Array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator-",921,G__TArray_7Dict_183_0_4, 117, G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+",919,G__TArray_7Dict_183_0_5, 117, G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7), -1, 0, 1, 1, 1, 0, "u 'TArray_7' - 1 - Array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator-",921,G__TArray_7Dict_183_0_6, 117, G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7), -1, 0, 1, 1, 1, 0, "u 'TArray_7' - 1 - Array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator*",918,G__TArray_7Dict_183_0_7, 117, G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7), -1, 0, 1, 1, 1, 0, "u 'TArray_7' - 1 - Array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator/",923,G__TArray_7Dict_183_0_8, 117, G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7), -1, 0, 1, 1, 1, 0, "u 'TArray_7' - 1 - Array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Value",509,G__TArray_7Dict_183_0_9, 102, -1, -1, 1, 7, 1, 1, 0, 
"i - - 0 - ix i - - 0 - iy "
"i - - 0 - iz i - - 0 - it "
"i - - 0 - ii i - - 0 - ij "
"i - - 0 - ik", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TArray_7Dict_183_0_10, 85, G__get_linked_tagnum(&G__TArray_7DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&TArray_7::Class), 0);
   G__memfunc_setup("Class_Name",982,G__TArray_7Dict_183_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TArray_7::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__TArray_7Dict_183_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&TArray_7::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__TArray_7Dict_183_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&TArray_7::Dictionary), 0);
   G__memfunc_setup("IsA",253,G__TArray_7Dict_183_0_14, 85, G__get_linked_tagnum(&G__TArray_7DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__TArray_7Dict_183_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__TArray_7Dict_183_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TArray_7Dict_183_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TArray_7Dict_183_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TArray_7::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TArray_7Dict_183_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TArray_7::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__TArray_7Dict_183_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TArray_7::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TArray_7Dict_183_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TArray_7::DeclFileLine), 0);
   // automatic destructor
   G__memfunc_setup("~TArray_7", 871, G__TArray_7Dict_183_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTArray_7Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();


   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTArray_7Dict() {
  G__cpp_setup_global0();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTArray_7Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TArray_7DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TArray_7DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TArray_7DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TArray_7DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TArray_7DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__TArray_7DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TArray_7DictLN_TArray_7 = { "TArray_7" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTArray_7Dict() {
  G__TArray_7DictLN_TClass.tagnum = -1 ;
  G__TArray_7DictLN_TBuffer.tagnum = -1 ;
  G__TArray_7DictLN_TMemberInspector.tagnum = -1 ;
  G__TArray_7DictLN_TObject.tagnum = -1 ;
  G__TArray_7DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__TArray_7DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TArray_7DictLN_TArray_7.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTArray_7Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__TArray_7DictLN_TClass);
   G__get_linked_tagnum(&G__TArray_7DictLN_TBuffer);
   G__get_linked_tagnum(&G__TArray_7DictLN_TMemberInspector);
   G__get_linked_tagnum(&G__TArray_7DictLN_TObject);
   G__get_linked_tagnum(&G__TArray_7DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__TArray_7DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__TArray_7DictLN_TArray_7),sizeof(TArray_7),-1,65024,"A Class for Array for Acceptance in eg2.",G__setup_memvarTArray_7,G__setup_memfuncTArray_7);
}
extern "C" void G__cpp_setupTArray_7Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTArray_7Dict()");
  G__set_cpp_environmentTArray_7Dict();
  G__cpp_setup_tagtableTArray_7Dict();

  G__cpp_setup_inheritanceTArray_7Dict();

  G__cpp_setup_typetableTArray_7Dict();

  G__cpp_setup_memvarTArray_7Dict();

  G__cpp_setup_memfuncTArray_7Dict();
  G__cpp_setup_globalTArray_7Dict();
  G__cpp_setup_funcTArray_7Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTArray_7Dict();
  return;
}
class G__cpp_setup_initTArray_7Dict {
  public:
    G__cpp_setup_initTArray_7Dict() { G__add_setup_func("TArray_7Dict",(G__incsetup)(&G__cpp_setupTArray_7Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTArray_7Dict() { G__remove_setup_func("TArray_7Dict"); }
};
G__cpp_setup_initTArray_7Dict G__cpp_setup_initializerTArray_7Dict;

